# Generated by Django 5.2.15 on 2026-06-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, verbose_name='เลขติดตามพัสดุ (Tracking Number)')),
                ('carrier', models.CharField(max_length=50, verbose_name='ผู้ให้บริการขนส่ง')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่าจัดส่ง')),
                ('status', models.CharField(choices=[('preparing', 'กำลังเตรียมสินค้า'), ('shipping', 'อยู่ระหว่างจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('returned', 'ส่งคืนสินค้า')], default='preparing', max_length=20, verbose_name='สถานะขนส่ง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุดเมื่อ')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='storefront.order', verbose_name='ออเดอร์')),
            ],
        ),
    ]
