# Generated by Django 5.2.15 on 2026-06-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสคูปอง')),
                ('discount_type', models.CharField(choices=[('percentage', 'เปอร์เซ็นต์ส่วนลด (%)'), ('fixed', 'จำนวนเงินส่วนลด (บาท)')], default='percentage', max_length=20, verbose_name='ประเภทส่วนลด')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='มูลค่าส่วนลด')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดซื้อขั้นต่ำ')),
                ('active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('start_date', models.DateTimeField(verbose_name='วันที่เริ่มต้น')),
                ('end_date', models.DateTimeField(verbose_name='วันที่สิ้นสุด')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='เบอร์โทรศัพท์')),
                ('points', models.IntegerField(default=0, verbose_name='แต้มสะสม')),
            ],
        ),
    ]
