# Generated by Django 5.2.15 on 2026-06-30 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storefront_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ส่วนลด')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาสุทธิ')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะออเดอร์')),
                ('payment_method', models.CharField(choices=[('credit', 'บัตรเครดิต/เดบิต'), ('promptpay', 'QR PromptPay'), ('cod', 'เก็บเงินปลายทาง (COD)')], default='promptpay', max_length=20, verbose_name='วิธีการชำระเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สั่งซื้อเมื่อ')),
            ],
            options={
                'db_table': 'storefront_order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU สินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต้นทุน')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
            ],
            options={
                'db_table': 'storefront_product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.product')),
            ],
            options={
                'db_table': 'storefront_orderitem',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.product')),
            ],
            options={
                'db_table': 'storefront_cartitem',
            },
        ),
    ]
